packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@types/node": ^24
  "@types/three": ^0.183.1
  "@vitejs/plugin-vue": ^6.0.5
  bitecs: ^0.4.0
  three: ^0.183.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue-tsc: ^3.2.6

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
